# Generated by Django 4.0.1 on 2022-01-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('director', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Detective', 'Detective'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Anime', 'Anime')], max_length=100)),
            ],
        ),
    ]
