# Generated by Django 4.0.1 on 2022-01-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='date_filmed',
            field=models.DateField(null=True),
        ),
    ]
